### ISSUE TITLE
Actividad 4 Modelos de Negocio en la Web 3,0

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-jad#1]
[Practica 4  Modelo de Negocios en Web 3_0.pdf](https://github.com/user-attachments/files/17122438/Practica.4.Modelo.de.Negocios.en.Web.3_0.pdf)

**Comment by MarcoRg06** [comment]
De acuerdo con la rúbrica obtuvieron 19%

**Comment by josealfredo79** [comment]
bien hecho y revisado...
